export const UPDATE_STATS = "UPDATE_STATS";
export const TOGGLE_IS_START = "TOGGLE_IS_START";
export const TOGGLE_IS_FINISH = "TOGGLE_IS_FINISH";
export const SET_START_TIME = "SET_START_TIME";
export const UPDATE_RACE_TIME = "UPDATE_RACE_TIME";
